### ISSUE TITLE
No module named builtins

### ISSUE THREAD

**Issue by Chartres** [datamade/dedupe#374]
Hi, 
I installed dedupe in Anaconda Python 2.7 on Windows 7 by downloading the repository, installing requirements, running the cython script, and then running setup.py develop, but I get this error whenever I want to run a test. Any ideas? Thanks!
```shell
C:\Users\dravecpa\Documents\SW\dedupe-master>python tests/test_dedupe.py
Traceback (most recent call last):
  File "tests/test_dedupe.py", line 3, in <module>
    import dedupe
  File "C:\Users\dravecpa\Documents\SW\Anaconda\lib\site-packages\dedupe-0.8.0.0.8-py2.7-win-amd64.egg\dedupe\__init__.py", line 6, in <module>
    from dedupe._init import *
  File "C:\Users\dravecpa\Documents\SW\Anaconda\lib\site-packages\dedupe-0.8.0.0.8-py2.7-win-amd64.egg\dedupe\_init.py", line 1, in <module>
    from dedupe.api import StaticDedupe, Dedupe
  File "C:\Users\dravecpa\Documents\SW\Anaconda\lib\site-packages\dedupe-0.8.0.0.8-py2.7-win-amd64.egg\dedupe\api.py", line 24, in <module>
    import dedupe.sampling as sampling
  File "C:\Users\dravecpa\Documents\SW\Anaconda\lib\site-packages\dedupe-0.8.0.0.8-py2.7-win-amd64.egg\dedupe\sampling.py", line 2, in <module>
    from builtins import range, zip
ImportError: No module named builtins
```

**Comment by fgregg** [comment]
builtins is part of the future package, did that not install when you ran
setup.py? https://pypi.python.org/pypi/future

**Comment by Chartres** [comment]
It did, but there must have been a problem with it, I forced an upgrade with `pip install future --upgrade` and it works now! Thanks! :)
```powershell
C:\Users\dravecpa\Documents\SW\dedupe-master>pip install future
Requirement already satisfied (use --upgrade to upgrade): future in c:\users\dravecpa\documents\sw\anaconda\lib\site-packages

C:\Users\dravecpa\Documents\SW\dedupe-master>pip install future --upgrade
Collecting future from https://pypi.python.org/packages/source/f/future/future-0.14.3.tar.gz#md5=e94079b0bd1fc054929e8769fc0f6083
  Using cached future-0.14.3.tar.gz
Installing collected packages: future
  Found existing installation: future 0.13.1
    DEPRECATION: Uninstalling a distutils installed project (future) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling future-0.13.1:
      Successfully uninstalled future-0.13.1
  Running setup.py install for future
    Installing pasteurize-script.py script to C:\Users\dravecpa\Documents\SW\Anaconda\Scripts
    Installing pasteurize.exe script to C:\Users\dravecpa\Documents\SW\Anaconda\Scripts
    Installing futurize-script.py script to C:\Users\dravecpa\Documents\SW\Anaconda\Scripts
    Installing futurize.exe script to C:\Users\dravecpa\Documents\SW\Anaconda\Scripts
Successfully installed future-0.14.3
```

**Comment by parautenbach** [comment]
Hello

Just ran into the same issue installing `dedupe-0.8.0.1.0` with `pip`, also using Anaconda and Python 2.7. Would it be possible to explicitly include the correct `future` package version in `setup.py` to make the installation more seamless?

I was confused for a moment, because I first installed dedupe without a version spec (which gave me v0.8.0), but then doing `import dedupe` from iPython gave me the `ImportError`. I then installed `csvdedupe`, after which my import suddenly worked, but I failed to notice that it's dependency is an older version, `dedupe==0.7.3.2`, which I assume does not import Python 3's `builtins` module, and hence the reason that I could then do `import dedupe`. 

Uninstalling everything and only running `pip install future --upgrade` (which gives me `future-0.14.3`) followed by `pip install dedupe`, everything works fine, as noted in the previous post.

PS: I'm running OS X.
