### ISSUE TITLE
Treat Null and empty string values as same?

### ISSUE THREAD

**Issue by primoz-k** [datamade/dedupe#460]
Just a thought:
Would it be better to treat null values and empty string values like they are the same?

I'm having problems with deduplication in Postgres with Dedupe, because I have to convert all empty strings into Null values and I want to avoid that.

**Comment by fgregg** [comment]
I think that we've learned that it is better to have a single value for missing variables. Since not all variables are strings, we landed on `None`

Can you convert to nulls when you pull the data into dedupe, using [NULLIF](http://www.postgresql.org/docs/8.4/static/functions-conditional.html#AEN15302)

**Comment by primoz-k** [comment]
OK, I agree with you. It is more universal if empty value is represented with `None`.

I did not know about `NULLIF`, will use it from now on. Thank you.
