### ISSUE TITLE
Uncertain pairs in active learning

### ISSUE THREAD

**Issue by ADiegoCAlonso** [datamade/dedupe#510]
While using the active learning part, I call `pair = deduper.uncertainPairs()` and I found two issues:
 1. The returned list with uncertain pairs contains only one element.
 2. The tuple order is switched when the second dataset is smaller than the first. For example if _data_1_  has 10000 entries and _data_2_ has 100 entries, the pair will be `[(item_from_data_2, item_from_data_1)]`

**Comment by fgregg** [comment]
Why do you think these are bugs?

**Comment by ADiegoCAlonso** [comment]
I actually don't know. Is this the expected behaviour?

**Comment by fgregg** [comment]
yes.

**Comment by fgregg** [comment]
Is the order of the items important to you? If so, why?

**Comment by fgregg** [comment]
If you need more than one pair, just call uncertainPairs multiple times.

**Comment by ADiegoCAlonso** [comment]
It would be nicer that `uncertainPairs()` returns a single pair that maintains the original order, like `(item_from_data_1, item_from_data_2)`.

However, as long as this is the expected behaviour, I can do workarounds for both issues. So, thank you for your time and fast reply.

**Comment by Gaurabh-Singhvi** [comment]
Hey! I am trying to build a GUI based on the dedupe package. I came across this thread only today. I have a few questions related to it.
1) uncertainPairs() gives me only one pair every time I call it as much as I understand. My question would be a) how to ensure that these pairs do not repeat themselves as I keep calling the uncertainPairs() function multiple times. b) how should i go about the active learning? should i keep passing every possible pair from uncertainPairs() into markPairs() as soon as I get it labeled from the user, or can i ask the user to label 30 pairs and then send them into markPairs at once? 

Any help will be appreciated a lot.

Thanks

**Comment by fgregg** [comment]
1. uncertainPairs will not repeat itself.
2. you can markPairs whenever you want. marPairs updates the activeLearner, so if you you won't do any learning until you markPairs.

**Comment by Gaurabh-Singhvi** [comment]
Okay sounds great. i'll just summarize the process once given that I am new to using the package. Let me know if I can better my flow. 

1st step: I will call the uncertainPairs function and display it for the user to label. 
2nd step: I will then pass this labeled example to markPairs() in the required format.
3rd step: I will again call the uncertainPair() function again which will now give me a better pair since i have sent the labelled pair already in the 2nd step. This process will be repeated until the user is satisfied with the training.
4th step: Now call the train function followed by the match function.

Seems logical right? Thanks a lot in advance!

**Comment by fgregg** [comment]
That will work.

**Comment by Gaurabh-Singhvi** [comment]
Thank you so much! I was actually going through your documentation for the dedupe package. Great work!  Thanks a lot for such quick replies. :) :+1:

**Comment by Genussradler** [comment]
is the following workflow possible with the dedupe object?

1. sample() some data
2. collect some uncertainPairs() and save them in another application (database). at this point the dedupe object will be destroyed
3. at a time later the user will mark some pairs in a gui and starts the training process
4. create a new dedupe object
5. sample() again some (maybe other) data
6. pass the marked pairs via markPairs()
7. train() the model

I'm not sure about this because the uncertain pairs based on other data (1.) than the trained data (5.)

**Comment by omansak** [comment]
@Genussradler @Gaurabh-Singhvi @fgregg do you know any solution about this? I need save uncertain pairs to databse with .net core web api and  user must mark that pair after repeat it. 

I have .net core web service and python web service. .net core send file and fieldy to dedupe via python service after python service return single umcertainpair to .net core. .net core save this data to sql.  Now dedupe object from pythin service  is destroyed. Database has a single uncertainpair. After users mark rhus pair and answer saves to database. 

Now i should get new pair. Sould i again send and create dedupe object with file name and fields after markpair and again get new uncertain pair . This solutios is so awful and during long time.


 How do i get new uncertain pairs before dedupe object destroy? (Can anyone help me? I have homework like this)

**Comment by piyushank** [comment]
@Gaurabh-Singhvi . @fgregg 
How dedupe object can be retained until response is received from GUI. What technology 
U have used to build GUI

**Comment by mmcgarry92** [comment]
@Gaurabh-Singhvi were you able to create your GUI based on the dedupe package? I would love to ask you a couple of questions about it if you were.
