### ISSUE TITLE
Affine Gap Distance link is broken in docs

### ISSUE THREAD

**Issue by mdiscenza** [datamade/dedupe#536]
Affine Gap Distance link in documentation on the page [Matching Records Page](https://dedupe.readthedocs.io/en/latest/Matching-records.html) is broken. It's supposed to go to
https://dedupe.readthedocs.io/en/latest/Affine%20Gap%20Distance and apparently the page doesn't exist.

**Comment by louispotok** [comment]
Hm, I wonder where it's supposed to go! I'd guess either:
* https://github.com/datamade/affinegap
* https://en.wikipedia.org/wiki/Gap_penalty#Affine

The link on [this page](https://dedupe.readthedocs.io/en/latest/Variable-definition.html?highlight=affine) goes to the wiki page, so that's probably the intended target here as well.

**Comment by fgregg** [comment]
Yeah, a link to the wikipedia article would be good.
